name: Backend CD - build and push
concurrency:
  group: ${{ github.ref }}.backend
  cancel-in-progress: true
on:
  # CD should be able to run manually
  workflow_dispatch:
  # or when CI workflow completed
  workflow_run:
    workflows: [ "Backend CI - Tests and analysis" ]
    types:
      - completed
jobs:
  # docker image should only be built manually or when CI workflow succeeded on a push event
  # as we must not publish to docker hub on pull requests or when CI workflow is run manually
  backend-build-and-push:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push') }}
    name: Build and push backend docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4

      -
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      -
        name: Extract backend docker metadata
        id: backend-metadata-extraction
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-backend
          tags: |
            latest
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=long

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ steps.backend-metadata-extraction.outputs.tags }}
          labels: ${{ steps.backend-metadata-extraction.outputs.labels }}
          cache-from: type=gha # use previous builds github action cache
          cache-to: type=gha,mode=max