name: Test and generate coverage reports
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies with Maven
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn verify jacoco:report

      - name: Upload backend coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: ./back/target/site/jacoco
          retention-days: 7

      - name: Publish backend coverage report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./back/target/site/jacoco
          destination_dir: ./coverage-backend

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome browser
        id: install-chrome
        uses: browser-actions/setup-chrome@v1
       
      - name: Run tests with coverage
        env:
          CHROME_BIN: ${{ steps.install-chrome.outputs.chrome-path }}
        run: npm test -- --code-coverage --watch=false --browsers=ChromeHeadlessCI

      - name: Upload frontend coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: ./front/coverage/bobapp
          retention-days: 7

      - name: Publish frontend coverage report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./front/coverage/bobapp
          destination_dir: ./coverage-frontend

      - name: Upload frontend coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}